-- MySQL Script generated by MySQL Workbench
-- Sun Sep  2 21:23:47 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema arduino
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `arduino` ;

-- -----------------------------------------------------
-- Schema arduino
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `arduino` DEFAULT CHARACTER SET utf8 ;
USE `arduino` ;

-- -----------------------------------------------------
-- Table `arduino`.`ACCESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arduino`.`ACCESS` (
  `idACCESS` INT NOT NULL AUTO_INCREMENT,
  `nivel` INT NOT NULL,
  PRIMARY KEY (`idACCESS`),
  UNIQUE INDEX `idACCESS_UNIQUE` (`idACCESS` ASC) )
;

-- -----------------------------------------------------
-- Table `arduino`.`CARD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arduino`.`CARD` (
  `idCARD` INT NOT NULL AUTO_INCREMENT,
  `idACCESS` INT NOT NULL,
  `hash` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idCARD`),
  INDEX `fk_CARD_table11_idx` (`idACCESS` ASC) ,
  UNIQUE INDEX `idCARD_UNIQUE` (`idCARD` ASC) ,
  CONSTRAINT `fk_CARD_table11`
    FOREIGN KEY (`idACCESS`)
    REFERENCES `arduino`.`ACCESS` (`idACCESS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

-- -----------------------------------------------------
-- Table `arduino`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arduino`.`USER` (
  `idUSER` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `telefone` INT NULL,
  `idCARD` INT NOT NULL,
  PRIMARY KEY (`idUSER`),
  INDEX `fk_USER_CARD_idx` (`idCARD` ASC) ,
  UNIQUE INDEX `idUSER_UNIQUE` (`idUSER` ASC) ,
  CONSTRAINT `fk_USER_CARD`
    FOREIGN KEY (`idCARD`)
    REFERENCES `arduino`.`CARD` (`idCARD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

-- -----------------------------------------------------
-- Table `arduino`.`LOGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arduino`.`LOGS` (
  `idLOG` INT NOT NULL AUTO_INCREMENT,
  `hashCARD` VARCHAR(32) NOT NULL,
  `data` VARCHAR(20) NOT NULL,
  `granted` BINARY(1) NOT NULL,
  PRIMARY KEY (`idLOG`),
  UNIQUE INDEX `idLOG_UNIQUE` (`idLOG` ASC))
;

-- -----------------------------------------------------
-- Table `arduino`.`CARD_has_LOGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arduino`.`CARD_has_LOGS` (
  `CARD_idCARD` INT NULL,
  `LOGS_idLOG` INT NOT NULL,
  PRIMARY KEY (`CARD_idCARD`, `LOGS_idLOG`),
  INDEX `fk_CARD_has_LOGS_LOGS1_idx` (`LOGS_idLOG` ASC) ,
  INDEX `fk_CARD_has_LOGS_CARD1_idx` (`CARD_idCARD` ASC) ,
  CONSTRAINT `fk_CARD_has_LOGS_CARD1`
    FOREIGN KEY (`CARD_idCARD`)
    REFERENCES `arduino`.`CARD` (`idCARD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CARD_has_LOGS_LOGS1`
    FOREIGN KEY (`LOGS_idLOG`)
    REFERENCES `arduino`.`LOGS` (`idLOG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO ACCESS (nivel) VALUES
	(1), (2), (3), (4), (5);