/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Conexao;
import control.DaoAcesso;
import control.DaoCartao;
import control.DaoOperador;
import function.CPF;
import function.Email;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import jssc.SerialPort;
import jssc.SerialPortException;

/**
 *
 * @author ZnzDarck
 */
public class OperatorEdit extends javax.swing.JFrame {

    /**
     * Creates new form OperatorEdit
     */
    public OperatorEdit() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Operadores");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtOperatorCard = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxAccess = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnCriar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        btnReload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtOperatorCard.setEnabled(false);
        txtOperatorCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOperatorCardActionPerformed(evt);
            }
        });

        jLabel1.setText("Card *");

        jLabel2.setText("Nome *");

        jLabel3.setText("CPF");

        jLabel4.setText("E-mail");

        jLabel5.setText("Telefone");

        jLabel6.setText("* São campos obrigatórios");

        jLabel7.setText("Acesso");

        btnCriar.setText("Criar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel8.setText("ID");

        txtid.setEnabled(false);

        try {
            btnReload.setPreferredSize(new Dimension(40, 40));
            Image img = ImageIO.read(getClass().getResource("../icons/Reload.png"));
            btnReload.setIcon(new ImageIcon(img));
        } catch (Exception ex) {
            System.out.println(ex);
        }
        btnReload.setText(null);
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(cbxAccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCriar)
                                    .addComponent(btnSalvar)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtOperatorCard, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReload))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCriar, btnSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOperatorCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReload))
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxAccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCriar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnSalvar))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOperatorCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOperatorCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOperatorCardActionPerformed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        String u = validaCampos();
        if(u == null){
            daoOperador.insert(instanciarObjeto(), instanciarObjectoCard());
            Operator op = new Operator();
            super.dispose();
            op.setVisible(true);
        }else {
            JOptionPane.showMessageDialog(this,
                    u,
                    "Warning",
                    JOptionPane.WARNING_MESSAGE);
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnCriarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("admin","1234");
        conexao.setDriver("com.mysql.cj.jdbc.Driver");
        //conexao.conectar();
        daoOperador = new DaoOperador(conexao.conectar());
        daoCartao = new DaoCartao(conexao.conectar());
        daoAcesso = new DaoAcesso(conexao.conectar());
        try{
            ResultSet res = daoAcesso.getAll();
           
            while(res.next()){
                cbxAccess.addItem(res.getString("nivel"));
            }   
        }catch(SQLException e){
            System.out.println(e.toString());
        }
        if(btnCriar.isEnabled()){
            txtCpf.setEnabled(false);
            txtEmail.setEnabled(false);
            txtNome.setEnabled(false);
            txtTelefone.setEnabled(false);
            btnCriar.setEnabled(false);
            
            SerialPort serialPort = new SerialPort("/dev/ttyACM0");
            String str = null;
            try {
                serialPort.openPort();//Open serial port
                serialPort.setParams(115200, 
                        SerialPort.DATABITS_8,
                        SerialPort.STOPBITS_1,
                        SerialPort.PARITY_NONE);//Set params.
                
                while(true){
                    str = serialPort.readString();
                    if(str != null && str.length() > 31) {
                      break;
                    }
                }
                serialPort.closePort();
                txtOperatorCard.setText(str);
                txtCpf.setEnabled(!txtCpf.isEnabled());
                txtNome.setEnabled(!txtNome.isEnabled());
                txtTelefone.setEnabled(!txtTelefone.isEnabled());
                txtEmail.setEnabled(!txtEmail.isEnabled());
                btnCriar.setEnabled(!btnCriar.isEnabled());
            }
            catch (Exception ex) {
                System.out.println(ex);
            }
        } 

    }//GEN-LAST:event_formWindowOpened

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        model.Operator u =  instanciarObjeto();
        daoOperador.update(u.getId());
        daoOperador.insert(u, instanciarObjectoCard());
        Operator op = new Operator();
        super.dispose();
        op.setVisible(true);    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        txtOperatorCard.setText("");
        txtCpf.setEnabled(false);
        txtEmail.setEnabled(false);
        txtNome.setEnabled(false);
        txtTelefone.setEnabled(false);
        btnCriar.setEnabled(false);
        
        SerialPort serialPort = new SerialPort("/dev/ttyACM0");
        String str = null;
        try {
            serialPort.openPort();//Open serial port
            serialPort.setParams(115200, 
                        SerialPort.DATABITS_8,
                        SerialPort.STOPBITS_1,
                        SerialPort.PARITY_NONE);
            
            while(true){
                str = serialPort.readString();
                if(str != null && str.length() > 31) {
                    txtOperatorCard.setText(str);
                    break;
                }
            }
            serialPort.closePort();
            txtOperatorCard.setText(str);
            txtCpf.setEnabled(!txtCpf.isEnabled());
            txtNome.setEnabled(!txtNome.isEnabled());
            txtTelefone.setEnabled(!txtTelefone.isEnabled());
            txtEmail.setEnabled(!txtEmail.isEnabled());
            btnCriar.setEnabled(!btnCriar.isEnabled());
        }
        catch (Exception ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_btnReloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperatorEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperatorEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperatorEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperatorEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperatorEdit().setVisible(true);
            }
        });
                
    }
    private model.Operator instanciarObjeto (){
        model.Operator u = new model.Operator(txtNome.getText().trim(), txtOperatorCard.getText());
        if(!txtid.getText().isEmpty()){
            u.setId(Long.parseLong(txtid.getText()));
        }
        if(!(txtCpf.getText().trim()).isEmpty()){
            u.setCpf(txtCpf.getText());
        }
        if(!(txtEmail.getText().trim()).isEmpty()){
            u.setEmail(txtEmail.getText());
        }
        if(!(txtTelefone.getText().trim()).isEmpty()){
            u.setTelefone(Long.parseLong(txtTelefone.getText()));
        }
        return u;        
    }
    private model.Card instanciarObjectoCard (){
        model.Card c = new model.Card(txtOperatorCard.getText().trim(), new Long (cbxAccess.getSelectedIndex() + 1));
        
        return c;
    }
    private String validaCampos (){
        String u = null;
        try{
            ResultSet res = daoCartao.getByCartao(txtOperatorCard.getText().trim());
            if(res.next()){
                throw new Exception();
            }
                
        }catch(Exception e){
            u += " Cartão já está cadastrado com outro operador";
        }
        
        if((txtNome.getText().trim()).isEmpty()){
            u += "Noma é necessário";
        }
        if(!(txtEmail.getText().trim()).isEmpty()){
            Email email = new Email();
            if(!(email.validateEmail(txtEmail.getText().trim()))){
               u += " Email inválido"; 
            }
        }
        if (!(txtCpf.getText().trim()).isEmpty()){
            CPF cpf = new CPF();
            if(!(cpf.isCPF(txtCpf.getText().trim()))){
                u += " CPF inválido";
            }    
        }
        if (!(txtTelefone.getText().trim()).isEmpty()){
            try{
                Long.parseLong(txtTelefone.getText().trim());
            }catch(NumberFormatException e){
                u += " Apenas números";
            }
        }
        return u;
    }
    public void setAgr(Boolean i){
        if (i){
            btnCriar.setEnabled(true);
            btnSalvar.setEnabled(false);
        }else{
            btnCriar.setEnabled(false);
            btnSalvar.setEnabled(true);
        }
    }
    public void setDados (model.Operator u){
        txtCpf.setText(u.getCpf());
        txtEmail.setText(u.getEmail());
        txtNome.setText(u.getNome());
        txtOperatorCard.setText(u.getCard());
        if(u.getTelefone() != null){
            txtTelefone.setText(u.getTelefone().toString());
        }
        txtid.setText(u.getId().toString());
    }
    private ImageIcon createImageIcon(String path, String description) {
        java.net.URL imgURL = getClass().getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL, description);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxAccess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtOperatorCard;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
    private Conexao conexao = null;
    private DaoOperador daoOperador = null;
    private DaoCartao daoCartao = null;
    private DaoAcesso daoAcesso = null;
}
