/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Conexao;
import control.DaoCartao;
import control.DaoOperador;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;

/**
 *
 * @author ZnzDarck
 */
public class Operator extends javax.swing.JFrame {

    /**
     * Creates new form Operator
     */
    public Operator() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Operadores");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listOperators = new javax.swing.JList<>();
        btnOperatorNovo = new javax.swing.JButton();
        btnOperatorInativar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setViewportView(listOperators);

        btnOperatorNovo.setText("Novo");
        btnOperatorNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperatorNovoActionPerformed(evt);
            }
        });

        btnOperatorInativar.setText("Inativar");
        btnOperatorInativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperatorInativarActionPerformed(evt);
            }
        });

        jButton4.setText("Editar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOperatorNovo)
                    .addComponent(btnOperatorInativar)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnOperatorInativar, btnOperatorNovo, jButton4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOperatorNovo)
                        .addGap(18, 18, 18)
                        .addComponent(btnOperatorInativar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("admin","1234");
        conexao.setDriver("com.mysql.cj.jdbc.Driver");
        //conexao.conectar();
        daoOperador = new DaoOperador(conexao.conectar());
        daoCartao = new DaoCartao(conexao.conectar());
        atualizaLista();
    }//GEN-LAST:event_formWindowOpened

    private void btnOperatorInativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperatorInativarActionPerformed
        try{
            ResultSet res = daoOperador.getByNome(listOperators.getSelectedValue());
            while(res.next()){
                ResultSet resC =  daoCartao.getById(res.getLong("CARD_idCARD"));
                model.Operator u = null;
                while(resC.next()){
                    u = new model.Operator(res.getString("nome"), resC.getString("hash"));
                }
                u.setId(res.getLong("idUSER"));
                daoOperador.update(u.getId());
                atualizaLista();    
            }
        }catch(SQLException e){
            System.out.println(e.toString());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnOperatorInativarActionPerformed

    private void btnOperatorNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperatorNovoActionPerformed
        OperatorEdit oe = new OperatorEdit();
        super.dispose();
        oe.setAgr(true);
        oe.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnOperatorNovoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          try{ 
            ResultSet res = daoOperador.getByNome(listOperators.getSelectedValue());
            while(res.next()){
                
                ResultSet resc = daoCartao.getById(res.getLong("CARD_idCARD"));
                model.Card c = null;
                while(resc.next()){
                    c = new model.Card(resc.getString("hash"), resc.getLong("ACCESS_idACCESS"));
                }
                model.Operator u = new model.Operator(res.getString("nome"), c.getHash());
                u.setId(Long.parseLong(res.getString("idUSER")));
                u.setCpf(res.getString("cpf"));
                u.setEmail(res.getString("email"));
                u.setTelefone(res.getLong("telefone"));

                OperatorEdit oe = new OperatorEdit();
                oe.setDados(u,c);
               
                super.dispose();
                oe.setAgr(false);
                oe.setVisible(true);
            }
        }catch(SQLException e){
            System.out.println(e.toString());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operator().setVisible(true);
            }
        });
    }
    private void atualizaLista(){
        try{
            ResultSet res = daoOperador.getAll();
            DefaultListModel<String> temp = new DefaultListModel<>();
            while(res.next()){
                temp.addElement(res.getString("nome"));
            }
            listOperators.setModel(temp);
        }catch(SQLException e){
            System.out.println(e.toString());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOperatorInativar;
    private javax.swing.JButton btnOperatorNovo;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listOperators;
    // End of variables declaration//GEN-END:variables
    private Conexao conexao = null;
    private DaoOperador daoOperador = null;
    private DaoCartao daoCartao = null;
}
